### ISSUE TITLE
PV reused for multiple users

### ISSUE THREAD

**Issue by hwuethrich** [kvdi/kvdi#53]
First of all, thanks for this great project! :)

We noticed that im some case, the PV userdata configmap ends up containing the same PV names for multiple users. This results in multiple PVCs being created for the same PV when two users with the same PV in the configmap try to start a session at the same time.

Without digging too deep in the code, this might be a result of how Kubernetes handles PV: It looks like Kubernetes is reusing an existing (currenty unused) PVs whenever a new user is starting a session for the first time.

I already created a dedicated storage class with `reclaimPolicy: Retain`. Isn't this behaviour expected, as the PVs are released after each session and Kubernetes will just reuse them for any new PVC?

We are using Kubernetes v1.21.4 with the vsphere-csi plugin and the following config (deployed using the helm chart):

```yaml
...
userdataSpec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: vsphere-block-retain
  resources:
    requests:
      storage: 20Gi
...
```

Thanks for your help!
