### ISSUE TITLE
VDI stacked "Desktop is ready" on Google Kubernetes Engine. What is the reason?

### ISSUE THREAD

**Issue by mertcakmak2** [kvdi/kvdi#80]
![image](https://user-images.githubusercontent.com/21373505/186886905-ea6324d6-788e-4076-a8aa-311d07c47051.png)

**My template as below**

```
apiVersion: desktops.kvdi.io/v1
kind: Template
metadata:
  name: ubuntu-xfce
spec:
  desktop:
    image: ghcr.io/kvdi/ubuntu-xfce4:latest
    imagePullPolicy: IfNotPresent
    allowRoot: true
  proxy:
    allowFileTransfer: true
  dind: 
    image: "docker:19-dind" # Defaults to latest which may have issues depending on your runtime
  tags:
    os: ubuntu
    desktop: xfce4
	    applications: minimal
```
